run:
	R -e "rmarkdown::render('basic-deconvolution.Rmd',output_format='all')"
	R -e "rmarkdown::render('sc_vignette.Rmd',output_format='all')"
	R -e "rmarkdown::render('blood.Rmd',output_format='all')"	
